language: android
jdk: openjdk8
android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    
before_install:
  - chmod +x ./PlacesOfInterest/gradlew
  - echo yes | sdkmanager "build-tools;28.0.3"
script:
  - ./PlacesOfInterest/gradlew build

notifications:
  slack: placeofinterest:ZZyNweMd8nqEwgvmtph26Xfa
  on_success: change
  on_failure: always
  
